apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: git@github.com:evansabove/sampleapp-gitops.git
        revision: HEAD
        directories:
          - path: apps/myapp/overlays/*

  template:
    metadata:
      name: 'myapp-{{path.basename}}'

    spec:
      project: default

      source:
        repoURL: git@github.com:evansabove/sampleapp-gitops.git
        targetRevision: HEAD
        path: '{{path.path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
